name: Update Pi-hole Blocklist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get install -y wget
        pip install adblockparser

    - name: Run script
      run: |
        # URL of the Adblock Plus filter list
        url="https://raw.githubusercontent.com/sjhgvr/oisd/main/oisd_nsfw.txt"

        # Download the filter list
        wget -O adblock.txt $url

        # Convert the filter list to a Pi-hole blocklist
        grep -o '||.*^' adblock.txt | sed 's/||//;s/\^//' > pihole_blocklist.txt

        # Remove the downloaded filter list
        rm adblock.txt

    - name: Commit and push if it changed
      run: |
        git diff > /dev/null
        git config --global user.email "me@spydisec.online"
        git config --global user.name "spydisec"
        git commit -am "Pi-hole blocklist update" || exit 0
        git push
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
